### PR TITLE
NDA Editor with preview, edit, push to github and reuse

### PR DESCRIPTION
**Pull request by smpadhy**
* Reorganized the eapp/public/lib/ folder
* imported the alpaca form builder example demo to start working on the preview and edit interface.
* This is WIP branch not yet ready for merge

### CODE REVIEW

**Review by satra — COMMENTED** [review]
while it's fine to show the integration right now, the form editor shouldn't be a separate app, but a re-usable module that can be used by the nda app, the project planner, etc.,.

in the nda app, a selection list should be a list of radio buttons rather than a dropdown, since users should be able to see all choices simultaneously.

how to get client id and secret and where to put it should be explained in the readme.

**Comment by smpadhy** [comment]
Thank you. I agree. 
I am not not sure what is the best way to share client id and secret key yet. Since a developer who wants to contribute only needs it. Should I just ask them to contact me if they want the credentials?

**Comment by satra** [comment]
can't they generate their own client id and secret?

**Comment by smpadhy** [comment]
Yes, they can. They have to register the app with github app.  In that case multiple brainverse apps will be registered with github with different clientId and secret key. What is not clear from their documentation is if registering the app is one time operation and required to be unique.  I guess, we need to just try out that registering the brainverse app from a different github account.

**Comment by satra** [comment]
how are we doing with the NDA editor? is it ready?

**Comment by smpadhy** [comment]
All the edits (schema and options) from the form editor are now converted to NDA data model and saved locally in a JSON file. Started working on the github push.

**Comment by smpadhy** [comment]
@satra you can review to merge the branch to master. It has all features as we discussed - preview, edit,github push (Repronim/ni-terms common repo and  forked repo), create github pull request, save to local and pulling data dictionary from four sources.

**Comment by smpadhy** [comment]
@satra Can I merge this branch?

**Pull request merged**
